#!/bin/bash

echo "Provisioning server..."

# Instalace základních balíčků
echo "Instalace základních balíčků..."
sudo yum install -y epel-release
sudo yum install -y httpd mariadb-server wget

# Instalace Zabbix repozitáře a balíčků
echo "Instalace Zabbix repozitáře a balíčků..."
sudo rpm -Uvh https://repo.zabbix.com/zabbix/7.0/rhel/7/x86_64/zabbix-release-7.0-1.el7.noarch.rpm
sudo yum install -y zabbix-server-mysql zabbix-agent2 zabbix-web-mysql zabbix-apache-conf

# Konfigurace databáze
echo "Konfigurace databáze..."
sudo systemctl enable mariadb --now
mysql -uroot -e "CREATE DATABASE zabbix CHARACTER SET utf8 COLLATE utf8_bin;"
mysql -uroot -e "CREATE USER 'zabbix'@'localhost' IDENTIFIED BY 'password';"
mysql -uroot -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';"
mysql -uroot -e "FLUSH PRIVILEGES;"
zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p'password' zabbix

# Konfigurace Zabbix serveru
echo "Konfigurace Zabbix serveru..."
sudo sed -i 's/# DBPassword=/DBPassword=password/' /etc/zabbix/zabbix_server.conf
sudo systemctl enable zabbix-server --now

# Nastavení Apache serveru
echo "Konfigurace Apache..."
sudo systemctl enable httpd --now

# Start Zabbix agenta
echo "Spuštění Zabbix agenta..."
sudo systemctl enable zabbix-agent2 --now

echo "Je to hotovy jak nikdy"